# Generated by Django 3.1.1 on 2020-09-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploads',
            name='image',
            field=models.FileField(upload_to='uploaded_images'),
        ),
        migrations.AlterField(
            model_name='knowledgedatabase',
            name='image',
            field=models.FileField(upload_to='known_images'),
        ),
    ]
