# Generated by Django 3.2.3 on 2021-05-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_api', '0002_auto_20200912_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageuploads',
            name='email',
            field=models.EmailField(default='jj@fd.com', max_length=100),
        ),
        migrations.AddField(
            model_name='knowledgedatabase',
            name='email',
            field=models.EmailField(default='jj@fd.com', max_length=100),
        ),
    ]
