# Generated by Django 3.2.3 on 2021-05-25 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_api', '0004_auto_20210525_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageuploads',
            name='timestamp',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
